module.exports = {
	googleMaps: "YOUR GOOGLE MAPS KEY HERE",
	uber: "YOUR UBER DEVELOPER KEY HERE",
	uberClientId: "YOUR UBER CLIENT ID HERE",
	uberClientSecret: "YOUR UBER CLIENT SECRET HERE",
	uberServerToken: "YOUR UBER SERVER TOKEN HERE",
	MONGODB_URI: 'YOUR MONGODB URI HERE',
	SECRET: 'YOUR SECRET KEY HERE'
};
